import { Component, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { Carteira, Page, Usuario } from '../../core/models/domain.models';
import { UsuarioService } from '../../core/services/usuario.service';
import { EmptyStateComponent, ErrorStateComponent, LoadingStateComponent, PaginationComponent } from '../../shared/components/ui-states.component';

@Component({ selector: 'app-usuario-detail-page', imports: [MatButtonModule, RouterLink, EmptyStateComponent, ErrorStateComponent, LoadingStateComponent, PaginationComponent], template: `<section class="detail-page">@if (loading()) {<app-loading-state message="Carregando usuário…"/>}@else if (error()) {<app-error-state [message]="error()" (retry)="load()"/>}@else if (user(); as currentUser) {<div class="page-heading detail-hero"><div><p class="eyebrow">Usuários</p><h1>{{ currentUser.nome }}</h1><p class="detail-hero__secondary">{{ currentUser.email }}</p></div></div><section class="detail-group"><h2>Carteiras vinculadas</h2>@if (!portfolios()?.content?.length) {<app-empty-state message="Este usuário ainda não possui carteiras."/>} @else {<div class="table-scroll"><table><thead><tr><th>Nome</th><th>Corretora</th><th>Ações</th></tr></thead><tbody>@for (item of portfolios()!.content; track item.id) {<tr><td>{{ item.nome }}</td><td>Corretora {{ item.corretoraId }}</td><td><a mat-button [routerLink]="['/carteiras', item.id]">Ver carteira</a></td></tr>}</tbody></table></div><app-pagination [page]="portfolios()!.number" [totalPages]="portfolios()!.totalPages" [first]="portfolios()!.first" [last]="portfolios()!.last" (previous)="loadPortfolios(portfolios()!.number - 1)" (next)="loadPortfolios(portfolios()!.number + 1)"/>}</section><a class="back-link" routerLink="/usuarios">Voltar para usuários</a>} </section>` })
export class UsuarioDetailPage { private readonly service = inject(UsuarioService); private readonly route = inject(ActivatedRoute); private readonly id = Number(this.route.snapshot.paramMap.get('id')); protected readonly user = signal<Usuario | null>(null); protected readonly portfolios = signal<Page<Carteira> | null>(null); protected readonly loading = signal(true); protected readonly error = signal(''); constructor() { this.load(); } protected load() { this.loading.set(true); this.error.set(''); this.service.get(this.id).subscribe({ next: (user) => { this.user.set(user); this.loadPortfolios(); }, error: (error: { message?: string }) => { this.error.set(error.message ?? 'Não foi possível carregar o usuário.'); this.loading.set(false); } }); } protected loadPortfolios(index = 0) { this.service.portfolios(this.id, { page: index, size: 10 }).subscribe({ next: (page) => { this.portfolios.set(page); this.loading.set(false); }, error: (error: { message?: string }) => { this.error.set(error.message ?? 'Não foi possível carregar as carteiras.'); this.loading.set(false); } }); } }
