import { Component, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatDialog } from '@angular/material/dialog';
import { RouterLink } from '@angular/router';
import { Corretora, Page } from '../../core/models/domain.models';
import { CorretoraService } from '../../core/services/corretora.service';
import { CorretoraDialogComponent } from '../../shared/components/registration-dialogs.component';
import { EmptyStateComponent, ErrorStateComponent, LoadingStateComponent, PaginationComponent } from '../../shared/components/ui-states.component';
import { ConfirmDialogComponent } from '../../shared/components/confirm-dialog.component';
import { FeedbackService } from '../../core/services/feedback.service';
import { maintenanceError } from '../../core/services/maintenance-error';

@Component({ selector: 'app-corretoras-page', imports: [MatButtonModule, MatMenuModule, RouterLink, ErrorStateComponent, EmptyStateComponent, LoadingStateComponent, PaginationComponent], template: `<section><div class="page-heading"><div><h1>Corretoras</h1><p>Instituições disponíveis para suas carteiras.</p></div><button mat-flat-button type="button" (click)="openDialog()">Cadastrar corretora</button></div>@if(loading()){<app-loading-state message="Carregando corretoras…"/>}@else if(error()){<app-error-state [message]="error()" (retry)="load()"/>}@else if(!page()?.content?.length){<app-empty-state message="Cadastre uma corretora para utilizá-la nas carteiras."/>}@else{<div class="table-scroll"><table><thead><tr><th>Nome</th><th>CNPJ</th><th>Cidade</th><th>Ações</th></tr></thead><tbody>@for(item of page()!.content;track item.id){<tr><td>{{item.nomeFantasia||item.razaoSocial||'—'}}</td><td>{{item.cnpj}}</td><td>{{item.cidade||'—'}}</td><td><a mat-button [routerLink]="['/corretoras',item.id]">Detalhes</a><button mat-button type="button" [matMenuTriggerFor]="brokerActions" [attr.aria-label]="'Mais ações para ' + (item.nomeFantasia||item.razaoSocial||item.cnpj)">Mais ações</button><mat-menu #brokerActions="matMenu"><button mat-menu-item type="button" (click)="remove(item)">Excluir corretora</button></mat-menu></td></tr>}</tbody></table></div><app-pagination [page]="page()!.number" [totalPages]="page()!.totalPages" [first]="page()!.first" [last]="page()!.last" (previous)="load(page()!.number-1)" (next)="load(page()!.number+1)"/>}</section>` })
export class CorretorasPage { private readonly service=inject(CorretoraService); private readonly dialog=inject(MatDialog); private readonly feedback=inject(FeedbackService); protected readonly page=signal<Page<Corretora>|null>(null);protected readonly loading=signal(true);protected readonly error=signal('');constructor(){this.load()}protected load(index=0){this.loading.set(true);this.error.set('');this.service.list({page:index,size:10,sort:'nomeFantasia,asc'}).subscribe({next:page=>{this.page.set(page);this.loading.set(false)},error:(e:{message?:string})=>{this.error.set(e.message??'Não foi possível carregar as corretoras.');this.loading.set(false)}})}protected openDialog(){this.dialog.open(CorretoraDialogComponent,{autoFocus:'first-tabbable',width:'min(100% - 2rem,32rem)'}).afterClosed().subscribe(created=>{if(created)this.load(this.page()?.number)})}protected remove(item: Corretora){const name=item.nomeFantasia||item.razaoSocial||item.cnpj;this.dialog.open(ConfirmDialogComponent,{data:{title:'Excluir corretora?',message:`Você está prestes a excluir "${name}". A corretora só poderá ser removida se não possuir registros vinculados.`,confirmLabel:'Excluir corretora'},autoFocus:'first-tabbable',width:'min(100% - 2rem,32rem)'}).afterClosed().subscribe(confirmed=>{if(!confirmed)return;this.service.delete(item.id).subscribe({next:()=>{this.feedback.success('Corretora excluída com sucesso.');this.page.update(current=>current?{...current,content:current.content.filter(entry=>entry.id!==item.id),totalElements:Math.max(current.totalElements-1,0)}:current)},error:(error:unknown)=>this.feedback.error(maintenanceError(error,'Não foi possível excluir a corretora.','Esta corretora não está mais disponível.'))})})}}
