import { Component, inject, signal } from '@angular/core';
import { ReactiveFormsModule, FormControl, FormGroup, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MAT_DIALOG_DATA, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { CarteiraService } from '../../core/services/carteira.service';
import { CorretoraService } from '../../core/services/corretora.service';
import { FeedbackService } from '../../core/services/feedback.service';
import { OperacaoService } from '../../core/services/operacao.service';
import { UsuarioService } from '../../core/services/usuario.service';
import { Corretora, PosicaoAcao, Usuario } from '../../core/models/domain.models';

@Component({selector:'app-corretora-dialog',imports:[ReactiveFormsModule,MatButtonModule,MatDialogModule],template:`<h2 mat-dialog-title>Cadastrar corretora</h2><form mat-dialog-content [formGroup]="form" (ngSubmit)="submit()"><label for="dialog-cnpj">CNPJ</label><input id="dialog-cnpj" formControlName="cnpj">@if(form.controls.cnpj.touched&&form.invalid){<p class="error">Informe o CNPJ.</p>}@if(error()){<p class="error" role="alert">{{error()}}</p>}<div mat-dialog-actions align="end"><button mat-button type="button" [disabled]="loading()" (click)="ref.close(false)">Cancelar</button><button mat-flat-button type="submit" [disabled]="form.invalid||loading()">{{loading()?'Cadastrando…':'Cadastrar'}}</button></div></form>`})
export class CorretoraDialogComponent{private readonly service=inject(CorretoraService);protected readonly ref=inject(MatDialogRef<CorretoraDialogComponent>);private readonly feedback=inject(FeedbackService);protected readonly loading=signal(false);protected readonly error=signal('');protected readonly form=new FormGroup({cnpj:new FormControl('',{nonNullable:true,validators:Validators.required})});protected submit(){if(this.form.invalid){this.form.markAllAsTouched();return}this.loading.set(true);this.service.create(this.form.getRawValue()).subscribe({next:()=>{this.feedback.success('Corretora cadastrada.');this.ref.close(true)},error:(e:{message?:string})=>{this.error.set(e.message??'Não foi possível cadastrar a corretora.');this.loading.set(false)}})}}

@Component({selector:'app-usuario-dialog',imports:[ReactiveFormsModule,MatButtonModule,MatDialogModule],template:`<h2 mat-dialog-title>Cadastrar usuário</h2><form mat-dialog-content [formGroup]="form" (ngSubmit)="submit()"><label for="dialog-nome">Nome</label><input id="dialog-nome" formControlName="nome" autocomplete="name"><label for="dialog-email">E-mail</label><input id="dialog-email" type="email" formControlName="email" autocomplete="email"><label for="dialog-senha">Senha</label><input id="dialog-senha" type="password" formControlName="senha" autocomplete="new-password">@if(form.touched&&form.invalid){<p class="error">Preencha todos os campos corretamente.</p>}@if(error()){<p class="error" role="alert">{{error()}}</p>}<div mat-dialog-actions align="end"><button mat-button type="button" [disabled]="loading()" (click)="ref.close(false)">Cancelar</button><button mat-flat-button type="submit" [disabled]="form.invalid||loading()">{{loading()?'Cadastrando…':'Cadastrar'}}</button></div></form>`})
export class UsuarioDialogComponent{private readonly service=inject(UsuarioService);protected readonly ref=inject(MatDialogRef<UsuarioDialogComponent>);private readonly feedback=inject(FeedbackService);protected readonly loading=signal(false);protected readonly error=signal('');protected readonly form=new FormGroup({nome:new FormControl('',{nonNullable:true,validators:Validators.required}),email:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.email]}),senha:new FormControl('',{nonNullable:true,validators:Validators.required})});protected submit(){if(this.form.invalid){this.form.markAllAsTouched();return}this.loading.set(true);this.service.create(this.form.getRawValue()).subscribe({next:()=>{this.feedback.success('Usuário cadastrado.');this.ref.close(true)},error:(e:{message?:string})=>{this.error.set(e.message??'Não foi possível cadastrar o usuário.');this.loading.set(false)}})}}

@Component({selector:'app-carteira-dialog',imports:[ReactiveFormsModule,MatButtonModule,MatDialogModule],template:`<h2 mat-dialog-title>Criar carteira</h2><form mat-dialog-content [formGroup]="form" (ngSubmit)="submit()"><label for="dialog-carteira">Nome</label><input id="dialog-carteira" formControlName="nome"><label for="dialog-usuario">Usuário</label><select id="dialog-usuario" formControlName="usuarioId"><option [ngValue]="0">Selecione</option>@for(item of users();track item.id){<option [ngValue]="item.id">{{item.nome}}</option>}</select><label for="dialog-corretora">Corretora</label><select id="dialog-corretora" formControlName="corretoraId"><option [ngValue]="0">Selecione</option>@for(item of brokers();track item.id){<option [ngValue]="item.id">{{item.nomeFantasia||item.razaoSocial||item.cnpj}}</option>}</select>@if(loadingOptions()){<p role="status">Carregando opções…</p>}@if(form.touched&&form.invalid){<p class="error">Informe o nome, usuário e corretora.</p>}@if(error()){<p class="error" role="alert">{{error()}}</p>}<div mat-dialog-actions align="end"><button mat-button type="button" [disabled]="loading()" (click)="ref.close(false)">Cancelar</button><button mat-flat-button type="submit" [disabled]="form.invalid||loading()||loadingOptions()">{{loading()?'Criando…':'Criar carteira'}}</button></div></form>`})
export class CarteiraDialogComponent {
  private readonly service = inject(CarteiraService);
  private readonly usersService = inject(UsuarioService);
  private readonly brokersService = inject(CorretoraService);
  protected readonly ref = inject(MatDialogRef<CarteiraDialogComponent>);
  private readonly feedback = inject(FeedbackService);
  protected readonly users = signal<Usuario[]>([]);
  protected readonly brokers = signal<Corretora[]>([]);
  protected readonly loadingOptions = signal(true);
  protected readonly loading = signal(false);
  protected readonly error = signal('');
  protected readonly form = new FormGroup({ nome: new FormControl('', { nonNullable: true, validators: Validators.required }), usuarioId: new FormControl(0, { nonNullable: true, validators: [Validators.required, Validators.min(1)] }), corretoraId: new FormControl(0, { nonNullable: true, validators: [Validators.required, Validators.min(1)] }) });
  private optionRequests = 0;

  constructor() {
    this.usersService.list({ size: 100, sort: 'nome,asc' }).subscribe({ next: (page) => { this.users.set(page.content); this.finishOptions(); }, error: () => this.failOptions() });
    this.brokersService.list({ size: 100, sort: 'nomeFantasia,asc' }).subscribe({ next: (page) => { this.brokers.set(page.content); this.finishOptions(); }, error: () => this.failOptions() });
  }

  private finishOptions() { this.optionRequests++; if (this.optionRequests === 2) this.loadingOptions.set(false); }
  private failOptions() { this.error.set('Não foi possível carregar usuários e corretoras.'); this.loadingOptions.set(false); }
  protected submit() {
    if (this.form.invalid) { this.form.markAllAsTouched(); return; }
    this.loading.set(true);
    this.service.create(this.form.getRawValue()).subscribe({
      next: () => { this.feedback.success('Carteira criada.'); this.ref.close(true); },
      error: (error: { message?: string }) => { this.error.set(error.message ?? 'Não foi possível criar a carteira.'); this.loading.set(false); },
    });
  }
}

interface OperationDialogData { carteiraId: number; positions: PosicaoAcao[]; }
@Component({selector:'app-compra-dialog',imports:[ReactiveFormsModule,MatButtonModule,MatDialogModule],template:`<h2 mat-dialog-title>Registrar compra</h2><form mat-dialog-content [formGroup]="form" (ngSubmit)="submit()"><label for="buy-asset">ID da ação</label><input id="buy-asset" type="number" min="1" formControlName="acaoId"><label for="buy-quantity">Quantidade</label><input id="buy-quantity" type="number" min="0.0001" step="any" formControlName="quantidade"><label for="buy-price">Preço unitário (opcional)</label><input id="buy-price" type="number" min="0.0001" step="any" formControlName="precoUnitario">@if(error()){<p class="error" role="alert">{{error()}}</p>}<div mat-dialog-actions align="end"><button mat-button type="button" [disabled]="loading()" (click)="ref.close(false)">Cancelar</button><button mat-flat-button type="submit" [disabled]="form.invalid||loading()">{{loading()?'Registrando…':'Registrar compra'}}</button></div></form>`})
export class CompraDialogComponent{private readonly data=inject<OperationDialogData>(MAT_DIALOG_DATA);private readonly service=inject(OperacaoService);protected readonly ref=inject(MatDialogRef<CompraDialogComponent>);private readonly feedback=inject(FeedbackService);protected readonly loading=signal(false);protected readonly error=signal('');protected readonly form=new FormGroup({acaoId:new FormControl(0,{nonNullable:true,validators:[Validators.required,Validators.min(1)]}),quantidade:new FormControl(0,{nonNullable:true,validators:[Validators.required,Validators.min(.0001)]}),precoUnitario:new FormControl<number|null>(null,Validators.min(.0001))});protected submit(){if(this.form.invalid){this.form.markAllAsTouched();return}this.loading.set(true);const value=this.form.getRawValue();this.service.buy({carteiraId:this.data.carteiraId,acaoId:value.acaoId,quantidade:value.quantidade,...(value.precoUnitario===null?{}:{precoUnitario:value.precoUnitario})}).subscribe({next:()=>{this.feedback.success('Compra registrada.');this.ref.close(true)},error:(e:{message?:string})=>{this.error.set(e.message??'Não foi possível registrar a compra.');this.loading.set(false)}})}}

@Component({selector:'app-venda-dialog',imports:[ReactiveFormsModule,MatButtonModule,MatDialogModule],template:`<h2 mat-dialog-title>Registrar venda</h2><form mat-dialog-content [formGroup]="form" (ngSubmit)="submit()"><label for="sell-asset">Ação</label><select id="sell-asset" formControlName="acaoId"><option [ngValue]="0">Selecione</option>@for(item of data.positions;track item.acaoId){<option [ngValue]="item.acaoId">{{item.ticker}} ({{item.quantidade}} disponíveis)</option>}</select><label for="sell-quantity">Quantidade</label><input id="sell-quantity" type="number" min="0.0001" step="any" formControlName="quantidade">@if(exceeds()){<p class="error">A quantidade excede a posição disponível.</p>}@if(error()){<p class="error" role="alert">{{error()}}</p>}<div mat-dialog-actions align="end"><button mat-button type="button" [disabled]="loading()" (click)="ref.close(false)">Cancelar</button><button mat-flat-button type="submit" [disabled]="form.invalid||loading()||exceeds()">{{loading()?'Registrando…':'Registrar venda'}}</button></div></form>`})
export class VendaDialogComponent{protected readonly data=inject<OperationDialogData>(MAT_DIALOG_DATA);protected readonly ref=inject(MatDialogRef<VendaDialogComponent>);private readonly service=inject(OperacaoService);private readonly feedback=inject(FeedbackService);protected readonly loading=signal(false);protected readonly error=signal('');protected readonly form=new FormGroup({acaoId:new FormControl(0,{nonNullable:true,validators:[Validators.required,Validators.min(1)]}),quantidade:new FormControl(0,{nonNullable:true,validators:[Validators.required,Validators.min(.0001)]})});protected exceeds(){const item=this.data.positions.find(p=>p.acaoId===this.form.controls.acaoId.value);return !!item&&this.form.controls.quantidade.value>item.quantidade}protected submit(){if(this.form.invalid||this.exceeds()){this.form.markAllAsTouched();return}this.loading.set(true);const value=this.form.getRawValue();this.service.sell({carteiraId:this.data.carteiraId,acaoId:value.acaoId,quantidade:value.quantidade}).subscribe({next:()=>{this.feedback.success('Venda registrada.');this.ref.close(true)},error:(e:{message?:string})=>{this.error.set(e.message??'Não foi possível registrar a venda.');this.loading.set(false)}})}}
